# Generated by Django 3.0.7 on 2020-06-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_TLDR',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_body',
            field=models.CharField(max_length=3000),
        ),
    ]
